services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Causal\Oidc\:
    resource: '../Classes/*'

  Causal\Oidc\Service\OAuthService:
    public: true

  Causal\Oidc\Service\OpenIdConnectService:
    public: true

  Causal\Oidc\Factory\RequestFactory:
    public: true

  Causal\Oidc\Factory\GenericOAuthProviderFactory:
    public: true

  Causal\Oidc\OidcConfiguration:
    public: true

  Causal\Oidc\EventListener\ProcessRequestTokenListener:
    tags:
      - name: event.listener
        identifier: 'causal/oidc-request-token'
        event: TYPO3\CMS\Core\Authentication\Event\BeforeRequestTokenProcessedEvent

  Causal\Oidc\EventListener\GetAuthorizationUrlSetLanguageEventListener:
    tags:
      - name: event.listener
        identifier: 'causal/oidc-get-authorization-url-set-language'
        event: Causal\Oidc\Event\GetAuthorizationUrlEvent



  # Causal\Oidc\Frontend\FrontendSimulationV13 instantiates two internal core classes via GeneralUtility::makeInstance
  TYPO3\CMS\Frontend\Page\PageInformationFactory:
    public: true
  TYPO3\CMS\Core\TypoScript\FrontendTypoScriptFactory:
    public: true
